bdr/urls.py
"""
Defines the URL structure for the Biological Data Repository Web application.

For more information, see
https://docs.djangoproject.com/en/1.6/topics/http/urls/
"""

from django.conf.urls import include, patterns, url

from views import HomeView, SearchView, AboutView, LegalView, search_script
from views.categories import (CategoryListView, CategoryDetailView, CategoryAddView,
                              CategoryEditView, CategoryDeleteView)
from views.datasets import (DatasetListView, DatasetDetailView, DatasetAddView, DatasetEditView,
                            DatasetDeleteView)
from views.files import FileListView, FileDetailView, FileUploadView, FileEditView, FileDeleteView
from views.filters import FilterAddView, FilterEditView, FilterDeleteView
from views.formats import FormatListView, dispatch as dispatch_format_view
from views.revisions import (RevisionDetailView, RevisionEditView, RevisionDeleteView, LatestRevisionRedirectView,
                             dispatch as dispatch_export_view)
from views.sources import (SourceListView, SourceDetailView, SourceAddView, SourceEditView,
                           SourceDeleteView)
from views.tags import TagListView, TagDetailView, TagAddView, TagEditView, TagDeleteView

__all__ = []
__author__ = "Michael Winter (mail@michael-winter.me.uk)"
__license__ = """
    Biological Dataset Repository: data archival and retrieval.
    Copyright (C) 2015  Michael Winter

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
    """

urlpatterns = patterns(
    '',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^about$', AboutView.as_view(), name='about'),
    url(r'^legal$', LegalView.as_view(), name='legal'),
    url(r'^search$', SearchView.as_view(), name='search'),

    url(r'^js/search.js$', search_script, name='search.js'),

    # Categories
    url(r'^categories/$', CategoryListView.as_view(), name='categories'),
    url(r'^categories/add$', CategoryAddView.as_view(), name='add-category'),
    url(r'^categories/(?P<name>[\w_-]+)-(?P<pk>\d+)/', include(patterns(
        '',
        url(r'^view$', CategoryDetailView.as_view(), name='view-category'),
        url(r'^edit$', CategoryEditView.as_view(), name='edit-category'),
        url(r'^delete$', CategoryDeleteView.as_view(), name='delete-category'),
    ))),

    # Tags
    url(r'^tags/$', TagListView.as_view(), name='tags'),
    url(r'^tags/add$', TagAddView.as_view(), name='add-tag'),
    url(r'^tags/(?P<name>[\w_-]+)-(?P<pk>\d+)/', include(patterns(
        '',
        url(r'^view$', TagDetailView.as_view(), name='view-tag'),
        url(r'^edit$', TagEditView.as_view(), name='edit-tag'),
        url(r'^delete$', TagDeleteView.as_view(), name='delete-tag'),
    ))),


    # Datasets
    url(r'^datasets/$', DatasetListView.as_view(), name='datasets'),
    url(r'^datasets/add$', DatasetAddView.as_view(), name='add-dataset'),
    url(r'^datasets/(?P<dataset>[\w_-]+)-(?P<dpk>\d+)/', include(patterns(
        '',
        url(r'^view$', DatasetDetailView.as_view(), name='view-dataset'),
        url(r'^edit$', DatasetEditView.as_view(), name='edit-dataset'),
        url(r'^delete$', DatasetDeleteView.as_view(), name='delete-dataset'),


        # Files
        url(r'^files/$', FileListView.as_view(), name='files'),
        url(r'^files/upload$', FileUploadView.as_view(), name='upload-file'),
        url(r'^files/(?P<filename>[\w_-]+)-(?P<fpk>\d+)/', include(patterns(
            '',
            url(r'^view$', FileDetailView.as_view(), name='view-file'),
            url(r'^edit$', FileEditView.as_view(), name='edit-file'),
            url(r'^delete$', FileDeleteView.as_view(), name='delete-file'),


            # Revisions
            # TODO: Implement revision views
            # url(r'^revisions/upload$', RevisionUploadView.as_view(), name='upload-revision'),
            url(r'^revisions/(?P<revision>\d+)-(?P<rpk>\d+)/', include(patterns(
                '',
                url(r'^view$', RevisionDetailView.as_view(), name='view-revision'),
                url(r'^edit$', RevisionEditView.as_view(), name='edit-revision'),
                url(r'^delete$', RevisionDeleteView.as_view(), name='delete-revision'),
                url(r'^export$', dispatch_export_view, {'view': 'export'}, name='export-revision'),
            ))),
            url(r'^revisions/latest/', include(patterns(
                '',
                url(r'^view$', LatestRevisionRedirectView.as_view(), dict(path='view'),
                    name='view-latest-revision'),
                url(r'^edit$', LatestRevisionRedirectView.as_view(), dict(path='edit'),
                    name='edit-latest-revision'),
                url(r'^delete$', LatestRevisionRedirectView.as_view(), dict(path='delete'),
                    name='delete-latest-revision'),
                url(r'^export$', LatestRevisionRedirectView.as_view(), dict(path='export'),
                    name='export-latest-revision'),
            ))),
        ))),


        # Sources
        url(r'^sources/$', SourceListView.as_view(), name='sources'),
        url(r'^sources/add$', SourceAddView.as_view(), name='add-source'),
        url(r'^sources/(?P<source>\d+)/', include(patterns(
            '',
            url(r'^view$', SourceDetailView.as_view(), name='view-source'),
            url(r'^edit$', SourceEditView.as_view(), name='edit-source'),
            url(r'^delete$', SourceDeleteView.as_view(), name='delete-source'),


            # Filters
            url(r'^filters/add$', FilterAddView.as_view(), name='add-filter'),
            url(r'^filters/(?P<filter>\d+)/', include(patterns(
                '',
                url(r'^edit$', FilterEditView.as_view(), name='edit-filter'),
                url(r'^delete$', FilterDeleteView.as_view(), name='delete-filter'),
            )))
        ))),
    ))),


    # Formats
    url(r'^formats/$', FormatListView.as_view(), name='formats'),
    url(r'^formats/create/(?P<type>[\w-]+)$', dispatch_format_view, {"view": "create"}, name='create-format'),
    url(r'^formats/(?P<pk>\d+)/', include(patterns(
        '',
        url(r'^view$', dispatch_format_view, {"view": "view"}, name='view-format'),
        url(r'^edit$', dispatch_format_view, {"view": "edit"}, name='edit-format'),
        url(r'^delete$', dispatch_format_view, {"view": "delete"}, name='delete-format'),
    ))),
)

bdr/models/base.py
"""
This module contains class definitions for the domain model of this
application.

The classes exported by this module include:

    Category
        Groups datasets into a hierarchical structure.
    Dataset
        A collection of data files maintained by the repository.
    File
        Represents the files that constitute each dataset.
    Filter
        Analyses (and optionally transforms) the names of files retrieved from
        data sources.
    Revision
        Represents revisions of files maintained by this repository.
    Source
        Represents a remote location that can be used to update one or more
        files within a dataset.
    Tag
        Annotate datasets, data files and revisions.
    Update
        Records updates made to the repository for each dataset.
"""

from datetime import datetime, timedelta
from urlparse import urlsplit
import re

from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.db import DatabaseError
from django.db.transaction import atomic
from django.db.models import Model, fields, SET_DEFAULT
from django.db.models.fields import files, related
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils.log import getLogger
from django.utils.text import slugify

from ..utils import utc, RemoteFile
from ..utils.archives import Archive
from ..utils.storage import delta_storage, upload_path
from ..utils.transports import Transport, TransportError

__all__ = ["Category", "Dataset", "File", "Filter", "Revision", "Source", "Tag", "Update"]
__author__ = "Michael Winter (mail@michael-winter.me.uk)"
__license__ = """
    Biological Dataset Repository: data archival and retrieval.
    Copyright (C) 2015  Michael Winter

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
    """


BACK_REFERENCE = re.compile(r"\\(\d{1,2})")
r"""
Matches back-references used in regular expression substitutions (e.g. \1).
"""

_log = getLogger('bdr.models.base')


def validate_regex(value):
    """
    Validate a string as a regular expression pattern.

    :param value: The regular expression pattern.
    :type value: str
    :raise re.error: if the pattern is invalid.
    """
    try:
        re.compile(value)
    except re.error as error:
        raise ValidationError("Invalid pattern: {0:s}".format(error))


class Category(Model):
    """
    Categories organise datasets into a hierarchical structure.

    The datasets belonging to a category can be retrieved using the
    :py:attr:`datasets` property of an instance.

    This class overrides the :py:meth:`~Model.get_absolute_url` method of the
    :py:class:`Model` class.
    """

    name = fields.CharField(max_length=50, unique=True)
    """The name of this category."""

    def get_absolute_url(self):
        """
        Return a URL that can be used to obtain more details about this
        category.
        """
        return reverse("bdr:view-category", kwargs={"pk": self.pk,
                                                    "name": slugify(unicode(self.name))})

    def __unicode__(self):
        return self.name

    class Meta(object):
        """Metadata options for the ``Category`` model class."""

        app_label = "bdr"
        ordering = ["name"]
        verbose_name_plural = "categories"


class Tag(Model):
    """
    Tags annotate datasets, data files and revisions.

    The entities associated with a given tag can be retrieved via their
    respective properties :py:attr:`datasets`, :py:attr:`datafiles` and
    :py:attr:`revisions`.

    This class overrides the :py:meth:`~Model.get_absolute_url` method of the
    :py:class:`Model` class.
    """

    name = fields.CharField(max_length=25, unique=True)
    """The name of this tag."""

    def get_absolute_url(self):
        """
        Return a URL that can be used to obtain more details about this tag.
        """
        return reverse("bdr:view-tag", kwargs={"pk": self.pk, "name": slugify(unicode(self.name))})

    @classmethod
    def get_field_names(cls):
        """
        Return the names of the fields in this model.

        :return: A list of field names belonging to this model.
        :rtype: list of unicode
        """
        return [field.name for field in cls._meta.concrete_fields]

    def __unicode__(self):
        return self.name

    class Meta(object):
        """Metadata options for the ``Tag`` model class."""

        app_label = "bdr"
        ordering = ["name"]


class Format(Model):
    """
    Represents the format of files stored in the repository.

    This class overrides the :py:meth:`~Model.get_absolute_url` method of the
    :py:class:`Model` class.
    """

    name = fields.CharField(max_length=50, unique=True, blank=False)
    """The name of the format."""
    entry_point_name = fields.CharField(max_length=150, editable=False)
    """
    The name of the plugin that provides the functionality related to this
    format.
    """
    metadata = fields.BinaryField(blank=True)
    """Parser-specific information for this format."""

    def __init__(self, *args, **kwargs):
        super(Format, self).__init__(*args, **kwargs)
        self._views = None

    @classmethod
    def default(cls):
        """Return the default (raw) format."""
        return Format.objects.get(pk=1)

    @property
    def deletable(self):
        """Return ``True`` if this format can be deleted."""
        return "delete" in self.views

    @property
    def editable(self):
        """Return ``True`` if this format can be edited."""
        return "edit" in self.views

    @property
    def views(self):
        """
        A dictionary describing views customised by this format.

        The possible views are:

            create:
                (Optional) A subclass of :py:class:``FormatCreateView`` used to
                reify a type of format.
            delete:
                (Optional) A subclass of :py:class:``FormatDeleteView`` used to
                delete an existing format.
            edit:
                (Optional) A subclass of :py:class:``FormatEditView`` used to
                edit the definition of an existing format.
            export:
                (Required) A subclass of :py:class:``RevisionExportView`` used
                to retrieve data from the repository.
            view:
                (Required) A subclass of :py:class:``FormatDetailView`` used to
                view details about an existing format.

        :rtype: dict of str
        """
        if self._views is None:
            from pkg_resources import iter_entry_points
            entry_point = list(iter_entry_points("bdr.views.formats", self.entry_point_name)).pop()
            self._views = entry_point.load()
        return self._views

    def convert(self, data, field_names, reader=None, **kwargs):
        """
        If a reader is not provided, the default implementation for this format
        will be used.

        :param data: The data file to convert.
        :type data: django.core.files.File
        :param field_names: The names of the fields to extract.
        :type field_names: list of (str | unicode)
        :param reader: (Optional) A reader capable of parsing the given file
                       into records.
        :type reader: bdr.formats.Reader | None
        :param kwargs: Additional options for performing the conversion.
        :type kwargs: dict of str
        :return: A iterable collection of records read
        :rtype: collections.Iterable of (str | unicode)
        """
        if reader is None:
            reader = self.reader(data)
        return self.converter(reader, field_names, **kwargs)

    def reader(self, data):
        """
        Return a :py:class:`Reader` over the given file using this format.

        :param data: A readable data file.
        :type data: django.core.files.File
        :return: A suitable ``Reader`` instance.
        :rtype: bdr.formats.Reader
        :raise ImportError: if this format does not have an associated Reader
                            class.
        """
        raise NotImplementedError()

    def converter(self, reader, field_names, **kwargs):
        """
        Return a :py:class:`Converter` over the given format reader.

        :param reader: A format reader.
        :type reader: Reader
        :param field_names: An iterable that contains the names of fields to be
                            read from ``reader``.
        :type field_names: list of str | tuple of str
        :param kwargs: Additional format-dependent arguments for initialising
                       the converter.
        :type kwargs: dict of str
        :return: A suitable ``Converter`` instance.
        :rtype: bdr.formats.Converter
        :raise ImportError: if this format does not have an associated
                            ``Converter`` class.
        """
        raise NotImplementedError()

    def get_absolute_url(self):
        """
        Return a URL that can be used to obtain more details about this format.
        """
        return reverse("bdr:view-format", kwargs={"pk": self.pk})

    def __unicode__(self):
        return self.name

    class Meta(object):
        """Metadata options for the ``Format`` model class."""

bdr/templates/bdr/about.html
{% extends 'bdr/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}About{% endblock %}

{% block main_content %}
    <nav>
        <ol class="breadcrumb small">
            <li><a href="{% url 'bdr:home' %}">Home</a></li>
            <li class="active">About</li>
        </ol>
    </nav>

    <header class="page-header col-sm-offset-0">
        <h1>About the Biological Data Repository</h1>
    </header>

    <section>
        <p>Research in the field of bioinformatics depends heavily upon biological data compiled in
            various datasets. While often public, these datasets vary considerably in format, access
            mechanisms, release frequency, and in the availability of previous releases. This latter
            point is of note as the ability to use old data to verify predictions in light of more
            recent updates offers a potent way to evaluate new methods.</p>
        <p>This repository retains prior revisions for such datasets which not only centralises
            these data sources, but also enables verification regardless of whether historical data
            is maintained by the original publisher. Given the variance in release schedules among
            datasets, updates are captured automatically to prevent the loss of data.</p>
    </section>
{% endblock %}

{% block footer %}
    <div class="col-xs-3 col-xs-offset-9 text-right">
        <span class="sr-only">In association with</span>
        <a href="http://www.royalholloway.ac.uk/">
            <img alt="Royal Holloway, University of London" src="{% static "bdr/images/rhul.jpg" %}"
                 height="110" width="220"></a><br>
        <span class="sr-only">and</span>
        <a href="http://www.paccanarolab.org/">
            <img alt="Paccanaro Lab" src="{% static "bdr/images/paccanarolab.png" %}"
                 height="33" width="220"></a>
    </div>
{% endblock %}

bdr/templates/bdr/base-sidebar.html
{% extends "bdr/base.html" %}

{% block main_content %}
    <aside id="sidebar" class="col-md-3">{% block sidebar %}{% endblock %}</aside>
    <article id="container" class="col-md-9">{% block content %}{% endblock %}</article>
{% endblock %}

bdr/templates/bdr/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% load staticfiles %}
<html lang="en">
<head>
    <title>{% block title %}Home{% endblock %} – Biological Dataset Repository</title>
    <link rel="icon" href="{% static "bdr/favicon.ico" %}" type="image/x-icon" />
    {% bootstrap_css %}
    {{ search_form.media.css }}
    {% block stylesheets %}{% endblock %}

    {% bootstrap_javascript %}
    {{ search_form.media.js }}
    {% block scripts %}{% endblock %}
</head>
<body class="container">
    <header id="header" class="row">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#main-navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'bdr:home' %}">
                    <img alt="" src="{% static "bdr/images/logo.png" %}" height="21" width="21">
                    Biological Dataset Repository
                </a>
            </div>
            <div id="main-navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            Manage <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'bdr:categories' %}">Categories</a></li>
                            <li><a href="{% url 'bdr:datasets' %}">Datasets</a></li>
                            <li><a href="{% url 'bdr:formats' %}">Formats</a></li>
                            <li><a href="{% url 'bdr:tags' %}">Tags</a></li>
                        </ul>
                    </li>
                </ul>

                {% if search_form %}
                <form class="repository-search navbar-form navbar-right" action="{% url 'bdr:search' %}"
                      method="get" role="search">
                    {% bootstrap_form search_form layout="inline" show_label=False %}
                </form>
                {% endif %}
            </div>
        </div>
    </nav>
    </header>

    <main class="row">
        {% block main_content %}{% endblock %}
    </main>

    <footer id="page-footer" class="row well">
        <ul id="footer-links" class="list-inline col-xs-9">
            <li><a href="{% url 'bdr:about' %}">About</a></li>
            <li><a href="{% url 'bdr:legal' %}">Legal</a></li>
            <li>&copy; 2015 Michael Winter</li>
        </ul>
        {% block footer %}{% endblock %}
    </footer>
</body>
</html>

bdr/templates/bdr/home.html
{% extends "bdr/base-sidebar.html" %}
{% load staticfiles %}
{% load humanize %}

{% block sidebar %}
    <nav>
        <h1>Datasets</h1>
        {% include "bdr/fragments/category_menu_block.html" with categories=category_list only %}
        {% include "bdr/fragments/dataset_menu_block.html" with datasets=dataset_list only %}

    {% if not category_list and not dataset_list %}
        <p>No datasets have been added yet.</p>
        <p>To <a href="{% url "bdr:add-dataset" %}">add a dataset</a>, go to the
            <a href="{% url "bdr:datasets" %}">datasets management page</a>.</p>
    {% endif %}
    </nav>
{% endblock %}

{% block content %}
    <nav>
        <ol class="breadcrumb small">
            <li class="active">Home</li>
        </ol>
    </nav>

    <header class="page-header">
        <h1>Home</h1>
        <p>The Biological Dataset Repository is an archive and centralised access point for
            research-related data. Each dataset can be configured to automatically update with the
            history of each file retained over time. A summary of recent repository activity is
            listed below.</p>
        {# <p>For more information about the organisation of the repository and its use, please see the <a href="{% url "bdr.frontend:help" %}">documentation</a>.</p> #}
    </header>

    <section>
        <h2>Recent Updates</h2>
    {% if update_list %}
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th class="col-xs-6">Dataset</th>
                    <th class="col-xs-2"># Revisions</th>
                    <th class="col-xs-4">Updated</th>
                </tr>
            </thead>
            <tbody>
            {% for update in update_list %}
                <tr>
                    <td><a href="{{ update.dataset.get_absolute_url }}">{{ update.dataset.name }}</a></td>
                    <td>{{ update.revisions.count }}</td>
                    <td>
                        <span title="Updated on {{ update.timestamp }}">{{ update.timestamp|naturaltime }}</span>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No datasets have been updated recently.</p>
    {% endif %}
    </section>
{% endblock %}

{% block footer %}
    <div class="col-xs-3 col-xs-offset-9 text-right">
        <span class="sr-only">In association with</span>
        <a href="http://www.royalholloway.ac.uk/">
            <img alt="Royal Holloway, University of London" src="{% static 'bdr/images/rhul.jpg' %}"
                 height="110" width="220"></a><br>
        <span class="sr-only">and</span>
        <a href="http://www.paccanarolab.org/">
            <img alt="Paccanaro Lab" src="{% static 'bdr/images/paccanarolab.png' %}"
                 height="33" width="220"></a>
    </div>
{% endblock %}

bdr/templates/bdr/legal.html
{% extends 'bdr/base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}Legal Information{% endblock %}

{% block main_content %}
    <nav>
        <ol class="breadcrumb small">
            <li><a href="{% url 'bdr:home' %}">Home</a></li>
            <li class="active">Legal Information</li>
        </ol>
    </nav>

    <header class="page-header col-sm-offset-0">
        <h1>Legal Information</h1>
    </header>

    <section>
        <h2>Copyright</h2>
        <p>The Biological Data Repository is Copyright &copy; 2015 Michael Winter. It is licensed
            under the terms of the
            <a href="https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html">GNU General
                Public License version 2 (or later)</a>.</p>
        <p>The data maintained herein remains the intellectual property
            (<abbr class="initialism">IP</abbr>) of the original authors and must be used in
            accordance with the applicable terms and conditions of each dataset.</p>

        <h2>Warranty</h2>
        <p>This program is distributed in the hope that it will be useful, but <em>without any
            warranty</em>; without even the implied warranty of <em>merchantability</em> or
            <em>fitness for a particular purpose</em>. See the GNU General Public License for more
            details.</p>

        <h2>Acknowledgements</h2>
        <p>This software uses the following <abbr class="initialism">IP</abbr> under license:</p>
        <ul>
            <li><a href="http://getbootstrap.com/">Bootstrap</a> is Copyright &copy; 2011–2015
                Twitter, Inc and licensed under the
                <a href="https://github.com/twbs/bootstrap/blob/master/LICENSE">MIT
                License</a>.</li>
            <li>The Flatly <a href="https://bootswatch.com/">Bootswatch</a> theme is Copyright
                &copy; 2014 Thomas Park and licensed under the
                <a href="https://github.com/thomaspark/bootswatch/blob/gh-pages/LICENSE">MIT
                License</a>.</li>
            <li><a href="https://www.djangoproject.com/">Django</a> is a trademark of the Django
                Software Foundation and licensed under the
                <a href="https://github.com/django/django/blob/master/LICENSE">BSD license</a>.</li>
            <li><a href="https://github.com/jcgregorio/httplib2">httplib2</a> is Copyright &copy;
                2006 Joe Gregorio and licensed under the
                <a href="https://github.com/jcgregorio/httplib2/blob/master/LICENSE">MIT
                License</a>.</li>
            <li><a href="http://jquery.com/">jQuery</a> is Copyright &copy; 2015 The jQuery
                Foundation and licensed under the
                <a href="https://github.com/jquery/jquery/blob/master/LICENSE.txt">MIT
                License</a>.</li>
            <li>The <a href="http://www.latofonts.com/">Lato</a> font is Copyright &copy; 2010–14
                &Lstrok;ukasz Dziedzic and licensed under the
                <a href="http://scripts.sil.org/OFL">SIL Open Font License version 1.1</a>.</li>
            <li>The logo for this website is a derivative work of an image released into the public
                domain by <a href="http://pixabay.com/">pixabay</a>.</li>
            <li><a href="https://www.python.org/">Python</a> is a trademark of the Python Software
                Foundation and licensed under the
                <a href="https://www.python.org/psf/license">Python License</a>.</li>
            <li>The <a href="http://www.royalholloway.ac.uk/">Royal Holloway, University of
                London</a> logo is a trademark of Royal Holloway, University of London.</li>
            <li><a href="https://github.com/twitter/typeahead.js">typeahead.js</a> is Copyright
                &copy; 2013–2014 Twitter, Inc and licensed under the
                <a href="https://github.com/twitter/typeahead.js/blob/master/LICENSE">MIT
                License</a>.</li>
            <li>The <a href="https://github.com/hyspace/typeahead.js-bootstrap3.less">typeahead.js
                compatibility stylesheet for Bootstrap 3</a> is Copyright &copy; 2014 Shawn Zhou and
                licensed under the <a href="https://github.com/hyspace/typeahead.js-bootstrap3.less/blob/master/LICENSE">MIT
                License</a>.</li>
            <li><a href="http://xdelta.org/">xdelta3</a> is Copyright &copy; 2001–07 Joshua
                Macdonald and licensed under the
                <a href="https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html">GNU
                General Public License version 2 (or later)</a>.</li>
        </ul>
    </section>
{% endblock %}

{% block footer %}
    <div class="col-xs-3 col-xs-offset-9 text-right">
        <span class="sr-only">In association with</span>
        <a href="http://www.royalholloway.ac.uk/">
            <img alt="Royal Holloway, University of London" src="{% static "bdr/images/rhul.jpg" %}"
                 height="110" width="220"></a><br>
        <span class="sr-only">and</span>
        <a href="http://www.paccanarolab.org/">
            <img alt="Paccanaro Lab" src="{% static "bdr/images/paccanarolab.png" %}"
                 height="33" width="220"></a>
    </div>
{% endblock %}